/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BaseMenu: typeof import('./src/components/Menu/BaseMenu.vue')['default']
    MessageDropdown: typeof import('./src/components/Message/MessageDropdown.vue')['default']
    ReDialog: typeof import('./src/components/ReDialog/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Src: typeof import('./src/components/ReImageVerify/src/index.vue')['default']
  }
}
